#! /bin/sh
### BEGIN INIT INFO
# Provides:				pintu-installer
# Required-Start:		redis-server
# Default-Start:		2 3 4 5
# Default-Stop:			0 1 6
# Short-Description:	Pintu Dependencies
# Description:			Pintu Dependencies - Sets up and validates dependencies for Pintu smart door bell.
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=pintu-installer
DESC=Pintu Installer
RUNDIR=/var/run/pintu
LOG=$RUNDIR/install.log

if [ -r /etc/default/pintu ]
then
	. /etc/default/pintu
fi

. /lib/lsb/init-functions

set -e

case "$1" in
	start)
		if [ -r $RUNDIR/install_ok ] ; then
			echo -n "Starting $DESC."
			cd $RUNDIR
			exit 0
		fi

		if [ -r $RUNDIR/install_error ] ; then
			echo "Unable to run $DESC due to previous failures."
			exit 1
		fi

		# 1. (Reserved for future custom Redis build)

		# 2. Install ZRAM, if not already installed
		if [ -z `cat /proc/swaps | grep zram` ] ; then 
			echo "Installing ZRAM" >> $LOG
			$PINTU_INSTALL_DIR/scripts/rpios64_02_install_zram.sh >> $LOG 2>&1 && 
			reboot || echo "ZRAM install failed!" > $RUNDIR/install_error
		fi

		# 3. Install OpenCV, if not already installed
		if [ -z `python3 -c "import cv2 ; print(cv2.__version__)"` ] ; then 
			echo "Installing OpenCV" >> $LOG
			$PINTU_INSTALL_DIR/scripts/rpios64_03_build_opencv.sh >> $LOG 2>&1 && 
			reboot || echo "OpenCV install failed!" > $RUNDIR/install_error
		; fi

		# 4. Install NCNN, if not already installed
		if [ -z `python3 -c "import ncnn ; print(ncnn.__version__)"` ] ; then
			echo "Installing NCNN" >> $LOG 
			$PINTU_INSTALL_DIR/scripts/rpios64_04_build_ncnn.sh  >> $LOG 2>&1 && 
			reboot || echo "NCNN install failed!" > $RUNDIR/install_error
		fi

		# 5. Install Pintu, if not already installed
		if [ -z `python3 -c "import pintu ; print(pintu.__version__)"` ] ; then 
			echo "Installing Pintu" >> $LOG
			python3 -m pip install $PINTU_INSTALL_DIR >> $LOG 2>&1 || 
			echo "Pintu install failed!" > $RUNDIR/install_error
			echo "Pintu install successful!" > $RUNDIR/install_ok
		fi
		;;

	stop)
		echo -n "Stopping $DESC: "
		;;

	restart|force-reload)
		${0} stop
		${0} start
		;;

	status)
		;;

	*)
		echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
		exit 1
		;;
esac

exit 0
