#! /bin/sh
### BEGIN INIT INFO
# Provides:				pintu-api
# Required-Start:		pintu-deps redis-server
# Default-Start:		2 3 4 5
# Default-Stop:			0 1 6
# Short-Description:	Pintu API
# Description:			Pintu API - API controls for Pintu smart door bell
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=pintu-api
DESC=Pintu API
RUNDIR=/var/run/pintu
PIDFILE=$RUNDIR/$NAME.pid

if [ -r /etc/default/pintu ]
then
	. /etc/default/pintu
fi

. /lib/lsb/init-functions

set -e

case "$1" in
	start)
		pintu-api &
		PID=$1
		echo $PID > $PIDFILE

	stop)
		echo -n "Stopping $DESC: "
		PID=$(head -n 1 $PIDFILE)
		echo -n "$DESC PID = $PID"
		kill $PID && rm $PIDFILE
		;;

	restart|force-reload)
		${0} stop
		${0} start
		;;

	status)
		PID=$(head -n 1 $PIDFILE)
		if [ -d /proc/$PID ]; then
			echo -n "$DESC ($PID) is not running."
		else
			echo -n "$DESC ($PID) is not running."
		fi
		;;

	*)
		echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
		exit 1
		;;
esac

exit 0
