#! /bin/sh
### BEGIN INIT INFO
# Provides:				pintu-detect
# Required-Start:		pintu-deps pintu-capture
# Default-Start:		2 3 4 5
# Default-Stop:			0 1 6
# Short-Description:	Pintu Detector	
# Description:			Pintu Detector - Object detector for Pintu smart door bell
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=pintu-api
DESC=Pintu API
RUNDIR=/var/run/pintu

if [ -r /etc/default/pintu ]
then
	. /etc/default/pintu
fi

. /lib/lsb/init-functions

set -e

case "$1" in
	start)
		if [ -r $RUNDIR/install_error ] ; then
			echo "Unable to run $DESC due to failed install."
			exit 1
		fi

		if [ -r $RUNDIR/install_ok ] ; then
			echo -n "Starting $DESC."

			cd $RUNDIR


			exit 0
		fi

		;;

	stop)
		echo -n "Stopping $DESC: "
		;;

	restart|force-reload)
		${0} stop
		${0} start
		;;

	status)
		;;

	*)
		echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
		exit 1
		;;
esac

exit 0
